<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>DiscordGarçom</AssemblyTitle>
    <Product>DiscordGarçom</Product>
    <Copyright>Copyright ©  2025</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Include=".config\App.config" />
    <None Include=".config\packages.config" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DSharpPlus" Version="5.0.0-nightly-02597" />
    <PackageReference Include="DSharpPlus.Commands" Version="5.0.0-nightly-02597" />
    <PackageReference Include="Lavalink4NET" Version="4.2.2" />
    <PackageReference Include="Lavalink4NET.Abstractions" Version="4.2.2" />
    <PackageReference Include="Lavalink4NET.DSharpPlus.Nightly" Version="4.2.2" />
    <PackageReference Include="Lavalink4NET.InactivityTracking" Version="4.2.2" />
    <PackageReference Include="Lavalink4NET.Integrations.Lavasearch" Version="4.2.2" />
    <PackageReference Include="Lavalink4NET.Integrations.Lavasrc" Version="4.2.2" />
    <PackageReference Include="Lavalink4NET.Rest" Version="4.2.2" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.10" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.ComponentModel.Composition" Version="10.0.10" />
  </ItemGroup>
</Project>