<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>GarçomDoKitts</AssemblyTitle>
    <Product>GarçomDoKitts</Product>
    <Copyright>Copyright ©  2025</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Include=".config\App.config" />
    <None Include=".config\packages.config" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DSharpPlus" Version="4.5.0" />
    <PackageReference Include="DSharpPlus.CommandsNext" Version="4.5.0" />
    <PackageReference Include="DSharpPlus.Lavalink" Version="4.5.0" />
    <PackageReference Include="DSharpPlus.SlashCommands" Version="4.5.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.ComponentModel.Composition" Version="9.0.3" />
  </ItemGroup>
</Project>